version: "3.8"
services:
  mysql-db:
    image: mysql
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 686110741Al
      MYSQL_DATABASE: topeducation
    ports:
      - 33061:3306
  app:
    container_name: topeducation
    image: arispiso/topeducation
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/topeducation?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=686110741Al
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db